name: Build and Release InTheWalls

on: [push]

jobs:
  Build-App:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Compile files
        run: javac -d out src/main/Main.java

#      - name: Export JAR artifact
#        uses: action/upload-artifact@v4
#        with:
#          name: InTheWalls-${}-jar
#          path: dist/